# -*- coding: utf-8 -*-
"""AppDI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EAjXblIc4G5ZApnUnAi_7LhZpZz7pfr1
"""



"""Fase 2: El Script Unificado (app.py)
Este es el código completo de tu aplicación. Puedes guardarlo como app.py si corres localmente

"""

import streamlit as st
from google.cloud import documentai
import os
import io

# --- Función Principal de Procesamiento ---
def process_document(project_id, location, processor_id, file_content, mime_type, key_content):
    """
    Función para procesar un documento usando la API de Document AI.
    Ahora también acepta el contenido de la clave JSON.
    """

    # Opciones de cliente para la API (regional)
    opts = {"api_endpoint": f"{location}-documentai.googleapis.com"}

    try:
        # Cargar las credenciales desde el contenido del archivo JSON
        client = documentai.DocumentProcessorServiceClient.from_service_account_info(
            key_content, client_options=opts
        )
    except Exception as e:
        st.error(f"Error al cargar las credenciales de GCP. Asegúrate de que el JSON es correcto. Detalle: {e}")
        return None, None

    # El nombre completo del recurso del procesador
    processor_name = client.processor_path(project_id, location, processor_id)

    # Cargar el contenido del archivo en la solicitud
    raw_document = documentai.RawDocument(
        content=file_content, mime_type=mime_type
    )

    # Configurar la solicitud a la API
    request = documentai.ProcessRequest(
        name=processor_name, raw_document=raw_document
    )

    try:
        # Enviar la solicitud de procesamiento
        result = client.process_document(request=request)
        document = result.document

        # Extraer las entidades (los datos que etiquetaste)
        extracted_data = {}
        for entity in document.entities:
            key = entity.type_
            #.mention_text es el texto real extraído
            value = entity.mention_text.strip()
            extracted_data[key] = value

        return extracted_data, document.text

    except Exception as e:
        st.error(f"Error al conectar con la API de Document AI: {e}")
        return None, None

# --- Interfaz de Streamlit ---

st.set_page_config(layout="wide")
st.title("Prueba de Concepto (PoC) TFM - ETB")
st.subheader("Extracción Inteligente de Datos de Contratos con Google Document AI")

# --- Barra Lateral (Sidebar) para Configuración ---
st.sidebar.header("Configuración de GCP")
st.sidebar.markdown("""
Esta PoC se conecta al Extractor Personalizado que entrenaste
en Document AI Workbench.[1]
""")

# Campos para que el usuario ingrese sus credenciales de GCP
gcp_project_id = st.sidebar.text_input("1. Project ID de GCP:")
gcp_location = st.sidebar.text_input("2. Location del Procesador (ej: us o eu):", "us")
gcp_processor_id = st.sidebar.text_input("3. Processor ID del Extractor:")
uploaded_key = st.sidebar.file_uploader("4. Sube tu JSON Key de Service Account:", type=["json"])

# --- Área Principal de la Aplicación ---

# 1. Carga del contrato
uploaded_contract = st.file_uploader("Carga tu contrato de muestra aquí (PDF):", type=["pdf"])

st.markdown("---")

# 2. Botón de procesamiento
if st.button("Procesar Contrato"):

    # Validaciones
    if not gcp_project_id:
        st.error("Error: Falta el Project ID de GCP en la barra lateral.")
    elif not gcp_location:
        st.error("Error: Falta la Location del procesador en la barra lateral.")
    elif not gcp_processor_id:
        st.error("Error: Falta el Processor ID en la barra lateral.")
    elif uploaded_key is None:
        st.error("Error: Sube el archivo JSON de la cuenta de servicio en la barra lateral.")
    elif uploaded_contract is None:
        st.error("Error: Sube un archivo PDF del contrato.")
    else:
        try:
            # --- Autenticación ---
            # Decodificar el contenido del archivo JSON subido
            key_dict = json.load(io.StringIO(uploaded_key.getvalue().decode("utf-8")))

            # --- Procesamiento ---
            st.info("Procesando documento... contactando a Google Document AI.")

            # Leer los bytes del archivo subido
            contract_bytes = uploaded_contract.read()

            # Llamar a la función principal
            extracted_data, full_text = process_document(
                project_id=gcp_project_id,
                location=gcp_location,
                processor_id=gcp_processor_id,
                file_content=contract_bytes,
                mime_type="application/pdf",
                key_content=key_dict  # Pasamos el diccionario de la clave
            )

            # --- Mostrar Resultados ---
            if extracted_data is not None:
                st.success("¡Documento procesado con éxito!")

                col1, col2 = st.columns(2)

                with col1:
                    st.subheader("Datos Estructurados Extraídos")
                    st.markdown("""
                    Estos son los campos clave que tu modelo de IA
                    identificó y extrajo.[2, 3]
                    """)
                    st.json(extracted_data)
                    st.markdown("""
                    **Valor para el TFM:** Esta salida JSON es el dato
                    estructurado que alimentaría los dashboards de BI
                    para los reportes de cumplimiento
                    automáticos.[4, 5]
                    """)

                with col2:
                    st.subheader("Texto Completo (OCR)")
                    st.markdown("Este es el texto completo extraído del documento.")
                    st.text_area("Texto OCR", full_text, height=400)

        except Exception as e:
            st.error(f"Ocurrió un error general: {e}")

